// @ts-check
//
// Mirrors the api, web and realtime-client configs. The reason for having one at all
// is the same reason those have one: `turbo run lint` skips a workspace with no
// `lint` script, and the audio and socket code in this repo spent a long time as the
// only unlinted source precisely because of that.
import eslint from '@eslint/js';
import eslintPluginPrettierRecommended from 'eslint-plugin-prettier/recommended';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      'eslint.config.mjs',
      'wxt.config.ts',
      // Generated by `wxt prepare` and `wxt build`.
      '.wxt/**',
      '.output/**',
      // Runs inside an AudioWorklet, which has neither DOM nor Node globals, and is
      // copied from @chatofy/realtime-client rather than written here.
      'public/worklets/**',
    ],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  eslintPluginPrettierRecommended,
  {
    languageOptions: {
      globals: {
        ...globals.browser,
        // `chrome`, plus WXT's auto-imported entrypoint helpers.
        chrome: 'readonly',
        defineBackground: 'readonly',
        defineContentScript: 'readonly',
      },
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    rules: {
      // As in the other three configs: these fire on `chrome.*` responses and on
      // JSON off a socket, where the shape is checked by a schema rather than by the
      // compiler.
      '@typescript-eslint/no-unsafe-assignment': 'warn',
      '@typescript-eslint/no-unsafe-member-access': 'warn',
      '@typescript-eslint/no-unsafe-argument': 'warn',
      '@typescript-eslint/no-unsafe-call': 'warn',
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
);
