-- The extension trigram search needs, created before the migration that indexes
-- with it.
--
-- The extension is created HERE rather than declared on the datasource: the
-- `extensions = [...]` form is deprecated as of Prisma 6.16 and this repo is on
-- 7. `postgres:16-alpine` — what both compose files and the CI service run —
-- ships contrib, so this succeeds there. A managed Postgres without pg_trgm
-- fails on THIS migration rather than on the one that creates history, which is
-- the point of keeping them separate.
--
-- No index is created here. The only GIN index this feature ships is the one
-- over the normalized `searchText` column, and that column does not exist yet —
-- it and its index arrive in the next migration. Creating per-column trigram
-- indexes here and dropping them there would make every deployment build
-- indexes it discards seconds later.
CREATE EXTENSION IF NOT EXISTS pg_trgm;
