import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { Slot } from 'radix-ui';

import { cn } from '../lib/utils.js';

/**
 * shadcn's Button, wearing this product's palette.
 *
 * Generated by the CLI and then re-skinned, which is the shape the whole shared
 * package takes: shadcn supplies the structure — cva, `asChild` through Radix's
 * Slot, the `data-slot`/`data-variant` attributes styling hooks hang off — and
 * the classes come from the tokens measured in `docs/design-guidelines.md`.
 *
 * Three things the stock component does that this one must not:
 *
 * `hover:bg-primary/90`. Fading a filled button on a dark ground reads as
 * disabled, not as hovered, and this product's dark palette is the default. Every
 * hover here is a real step along the token scale instead — `accent-hover` exists
 * for exactly this.
 *
 * `hover:bg-accent`. shadcn's `--accent` is a pale grey hover surface; this
 * project's "accent" is the brand blue, and there is no bare `--accent` token. The
 * mechanical substitution is `bg-secondary`, which already resolves to
 * `surfaceRaised` — the same role shadcn's accent plays.
 *
 * `dark:` variants. This palette is built on `light-dark()`, and the theme choice
 * is applied as a class only when someone picks one explicitly. The default —
 * "follow the machine" — carries no class, so a `dark:` utility never fires while
 * every `light-dark()` token still flips. A stock component's `dark:bg-input/30`
 * would render the light treatment on a dark ground for most users, silently.
 *
 * `live` is a variant of this product's own. It is not `destructive`, though they
 * currently carry the same fill: stopping a translation is the end of a running
 * state, not a destructive act, and the two will not always want the same
 * treatment.
 */
const buttonVariants = cva(
  cn(
    'inline-flex shrink-0 items-center justify-center gap-2 rounded-md',
    'text-body font-medium whitespace-nowrap outline-none',
    'transition-[color,background-color,box-shadow] duration-fast ease-standard',
    'motion-reduce:transition-none',
    'focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px]',
    'aria-invalid:border-destructive aria-invalid:ring-destructive/20',
    'disabled:pointer-events-none disabled:border-transparent disabled:opacity-45',
    "[&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
  ),
  {
    variants: {
      variant: {
        default: 'bg-primary text-primary-foreground hover:bg-accent-hover',
        // `live-fill`, not `live`. White on `live` is 3.91 and fails AA; on this
        // it is 4.93. These are the buttons that stop a recording, so they are
        // the last place to accept text you have to squint at.
        live: 'bg-live-fill text-on-live-fill hover:brightness-110',
        destructive: 'bg-live-fill text-on-live-fill hover:brightness-110',
        outline: 'border-border-control border bg-transparent hover:bg-secondary',
        secondary: 'bg-secondary text-secondary-foreground hover:bg-border',
        ghost: 'text-muted-foreground hover:bg-secondary hover:text-foreground',
        link: 'text-accent-text underline-offset-4 hover:underline',
      },
      size: {
        default: 'h-10 px-4 py-2 has-[>svg]:px-3',
        sm: 'h-9 px-3 has-[>svg]:px-2.5',
        lg: 'h-11 px-6 has-[>svg]:px-4',
        icon: 'size-10',
      },
    },
    defaultVariants: { variant: 'default', size: 'default' },
  },
);

function Button({
  className,
  variant = 'default',
  size = 'default',
  asChild = false,
  ...props
}: React.ComponentProps<'button'> &
  VariantProps<typeof buttonVariants> & {
    asChild?: boolean;
  }) {
  const Comp = asChild ? Slot.Root : 'button';

  return (
    <Comp
      data-slot="button"
      data-variant={variant}
      data-size={size}
      className={cn(buttonVariants({ variant, size, className }))}
      {...props}
    />
  );
}

export { Button, buttonVariants };
