/**
 * The React entry: components for the two DOM surfaces.
 *
 * Separate from the root export, and that separation is the whole point.
 * `apps/mobile` imports `@chatofy/ui` through Metro, which must never resolve
 * React, Radix or anything with a DOM type in it. Nothing here is reachable from
 * there — a subpath is only resolved when it is asked for by name.
 *
 * Not for the meeting overlay either, though for a different reason.
 * `apps/extension/entrypoints/content/` renders into a closed shadow root under
 * `:host { all: initial }`, which does not reset custom properties — so a
 * var()-themed overlay is repaintable by the meeting page it sits on.
 * `overlay-invariants.spec.ts` enforces that, and every Tailwind utility emits a
 * custom property. The overlay keeps its hand-written string.
 *
 * Every chunk built from this file carries `"use client"`, applied as a banner
 * rather than per file — see `tsup.react.config.ts`. Anything that needs to be
 * callable from a server component needs an entry of its own.
 */

// shadcn primitives, generated by the CLI and re-skinned to this project's tokens.
export { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from './accordion.js';
export { Alert, AlertDescription, AlertTitle } from './alert.js';
export {
  Avatar,
  AvatarBadge,
  AvatarFallback,
  AvatarGroup,
  AvatarGroupCount,
  AvatarImage,
} from './avatar.js';
export { Badge, badgeVariants } from './badge.js';
export { Button, buttonVariants } from './button.js';
export {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from './card.js';
export { Checkbox } from './checkbox.js';
export {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuPortal,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
  DropdownMenuSeparator,
  DropdownMenuShortcut,
  DropdownMenuSub,
  DropdownMenuSubContent,
  DropdownMenuSubTrigger,
  DropdownMenuTrigger,
} from './dropdown-menu.js';
export { Input } from './input.js';
export { Label } from './label.js';
export {
  Popover,
  PopoverAnchor,
  PopoverContent,
  PopoverDescription,
  PopoverHeader,
  PopoverTitle,
  PopoverTrigger,
} from './popover.js';
export { RadioGroup, RadioGroupItem } from './radio-group.js';
export {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectScrollDownButton,
  SelectScrollUpButton,
  SelectSeparator,
  SelectTrigger,
  SelectValue,
} from './select.js';
export { Separator } from './separator.js';
export {
  Sheet,
  SheetClose,
  SheetContent,
  SheetDescription,
  SheetFooter,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from './sheet.js';
export {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarGroup,
  SidebarGroupAction,
  SidebarGroupContent,
  SidebarGroupLabel,
  SidebarHeader,
  SidebarInput,
  SidebarInset,
  SidebarMenu,
  SidebarMenuAction,
  SidebarMenuBadge,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarMenuSkeleton,
  SidebarMenuSub,
  SidebarMenuSubButton,
  SidebarMenuSubItem,
  SidebarProvider,
  SidebarRail,
  SidebarSeparator,
  SidebarTrigger,
  useSidebar,
} from './sidebar.js';
export { Skeleton } from './skeleton.js';
export { Slider } from './slider.js';
export { Switch } from './switch.js';
export { Tabs, TabsContent, TabsList, TabsTrigger, tabsListVariants } from './tabs.js';
export { Toggle, toggleVariants } from './toggle.js';
export { ToggleGroup, ToggleGroupItem } from './toggle-group.js';
export { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from './tooltip.js';

// Compositions this product owns. They live here rather than in an app because
// both DOM surfaces render them, which is the criterion — not whether they are
// primitive.
export { DirectionToggle, type DirectionToggleLabels } from './direction-toggle.js';
export { SegmentedControl, type SegmentedOption } from './segmented-control.js';
export { StatusIndicator, type StatusTone } from './status-indicator.js';
export { ThemeToggle, type ThemeChoice } from './theme-toggle.js';

// Travels with DirectionToggle, and with `live-panel.tsx`, which is its second
// consumer. Deliberately not on the root export: `Intl.DisplayNames` is not
// guaranteed under Hermes.
export { languageName } from './lib/language-name.js';

export { cn } from '../lib/utils.js';
