'use client';

import * as React from 'react';
import { Slider as SliderPrimitive } from 'radix-ui';

import { cn } from '../lib/utils.js';

/**
 * A continuous value along a track.
 *
 * Generated by the shadcn CLI, then re-skinned. Same rules as `toggle.tsx`.
 *
 * `onValueChange` fires on every pointer move, which is what makes a slider feel
 * live — and what makes it expensive if a caller treats each tick as a commit.
 * Radix also exposes `onValueCommit`, firing once when the pointer or key is
 * released; a caller that persists to storage or hits the network belongs there,
 * and only the cheap live effect belongs in `onValueChange`. Both are passed
 * through untouched, so that decision stays with the caller rather than being
 * made here.
 *
 * ## Vertical works, and it did not before
 *
 * The hand-written version this replaces dropped every `data-[orientation]`
 * utility the CLI writes. `orientation="vertical"` still typechecked — it is
 * Radix's own prop — and rendered a track with a horizontal height on a Root with
 * no column direction. It compiled, it rendered, and it was wrong; nothing in the
 * source said so. The variants below are the CLI's, kept whole.
 *
 * ## What is not taken from the CLI
 *
 * Upstream's 4px focus ring. 3px is the rule across every control here and
 * `slider.spec.tsx` asserts it — a slider is operated by arrow keys as often as by
 * pointer, so the one control most used from the keyboard is the last place to
 * pick a private ring width. The hover ring follows it to the same 3px rather than
 * being dropped: two ring widths of equal specificity on a thumb that is both
 * hovered and focused would be settled by whichever Tailwind emitted last.
 *
 * `disabled:pointer-events-none disabled:opacity-50` on the thumb, which is dead
 * code upstream: the thumb is a span with `role="slider"`, and the `disabled:`
 * variant only matches form elements. Radix marks it `data-disabled`, so
 * `pointer-events-none` is rewritten to that. The `opacity-50` half is dropped
 * rather than rewritten — the Root already carries it, and a thumb that dimmed
 * again inside an already-dimmed Root would land at 0.25, which is only invisible
 * upstream because the variant never matched.
 *
 * A literal white fill on the thumb, which does not flip. `bg-card` is the token
 * that does, and it clears 1.4.11 against both track states — 3.34 and 3.36:1 on
 * an empty track, 6.50 and 5.86:1 on a filled one.
 *
 * The reduced-motion escape is required by `skin-guard.spec.ts`; the CLI writes
 * none.
 */
function Slider({
  className,
  defaultValue,
  value,
  min = 0,
  max = 100,
  ...props
}: React.ComponentProps<typeof SliderPrimitive.Root>) {
  // One thumb per value, because Radix renders exactly the thumbs it is given. A
  // fixed single thumb would typecheck against `value={[a, b]}` and then render a
  // range whose second handle cannot be grabbed or reached by keyboard — it
  // compiles, it renders, and it is silently unusable.
  const _values = React.useMemo(
    () => (Array.isArray(value) ? value : Array.isArray(defaultValue) ? defaultValue : [min, max]),
    [value, defaultValue, min, max],
  );

  return (
    <SliderPrimitive.Root
      data-slot="slider"
      defaultValue={defaultValue}
      value={value}
      min={min}
      max={max}
      className={cn(
        'relative flex w-full touch-none items-center select-none',
        'data-[disabled]:cursor-not-allowed data-[disabled]:opacity-50',
        'data-[orientation=vertical]:h-full data-[orientation=vertical]:min-h-44',
        'data-[orientation=vertical]:w-auto data-[orientation=vertical]:flex-col',
        className,
      )}
      {...props}
    >
      <SliderPrimitive.Track
        data-slot="slider-track"
        className={cn(
          'relative grow overflow-hidden rounded-full bg-muted',
          'data-[orientation=horizontal]:h-1.5 data-[orientation=horizontal]:w-full',
          'data-[orientation=vertical]:h-full data-[orientation=vertical]:w-1.5',
        )}
      >
        <SliderPrimitive.Range
          data-slot="slider-range"
          className={cn(
            'absolute bg-primary',
            'data-[orientation=horizontal]:h-full data-[orientation=vertical]:w-full',
          )}
        />
      </SliderPrimitive.Track>
      {Array.from({ length: _values.length }, (_, index) => (
        <SliderPrimitive.Thumb
          data-slot="slider-thumb"
          key={index}
          className={cn(
            'block size-4 shrink-0 rounded-full border border-primary bg-card',
            'shadow-elev-sm ring-ring/50',
            'transition-[color,box-shadow] duration-fast ease-standard',
            'motion-reduce:transition-none',
            'hover:ring-[3px] focus-visible:ring-[3px] focus-visible:outline-hidden',
            'data-[disabled]:pointer-events-none',
          )}
        />
      ))}
    </SliderPrimitive.Root>
  );
}

export { Slider };
