'use client';

import * as React from 'react';
import { Switch as SwitchPrimitive } from 'radix-ui';

import { cn } from '../lib/utils.js';

/**
 * An on/off control for a setting that takes effect on its own.
 *
 * Generated by the shadcn CLI, then re-skinned. Same rules as `toggle.tsx`.
 *
 * A Switch rather than a `Toggle`, and the distinction is not cosmetic: `Toggle`
 * renders a button with `aria-pressed`, which announces "pressed" and reads as an
 * action that was performed. A switch announces its state, which is what a setting
 * like "speak the translation" actually is. Radix gives the Root `role="switch"`
 * with `aria-checked` and a hidden bubble input, so it also participates in a form
 * the way a checkbox would.
 *
 * ## The unchecked track is `bg-input`, and the earlier `bg-muted` was wrong
 *
 * This file first shipped hand-written, and picked `--muted` for the off state on
 * the reasoning that an off switch should read as "nothing here" the way an empty
 * slider track does. Measured against the shipped palette that reasoning does not
 * survive: `muted` against the page is 1.07:1 in light and 1.20:1 in dark, and the
 * `card` thumb sitting on it is 1.10:1 and 1.11:1. An off switch was a boundary
 * only its border drew, with a thumb that had no boundary at all — under the 3:1
 * WCAG 1.4.11 asks of a component's visual state.
 *
 * The CLI's `--input` clears it on both axes: track against page 3.26 and 3.65:1,
 * thumb against track 3.34 and 3.36:1. Checked is better again — `card` on
 * `primary` is 6.50 and 5.86:1. So the border goes transparent, as upstream has
 * it, and the fill carries the boundary.
 *
 * ## What is not taken from the CLI
 *
 * `dark:data-[state=unchecked]:bg-input/80` and the two `dark:` thumb fills, which
 * `skin-guard.spec.ts` bans outright: this palette is `light-dark()` based and the
 * theme class is absent under "follow the machine", so those never fire. `bg-card`
 * flips on its own and clears both grounds, which is why no dark branch is needed.
 *
 * `transition-all`, which would ease the focus ring in — lag on the one control a
 * keyboard user is waiting to see respond. Both transitions name their properties.
 * The reduced-motion escape is required; the CLI writes none.
 */
function Switch({
  className,
  size = 'default',
  ...props
}: React.ComponentProps<typeof SwitchPrimitive.Root> & {
  size?: 'sm' | 'default';
}) {
  return (
    <SwitchPrimitive.Root
      data-slot="switch"
      data-size={size}
      className={cn(
        'peer group/switch inline-flex shrink-0 items-center rounded-full border border-transparent',
        'shadow-elev-sm',
        'transition-[background-color,border-color,box-shadow] duration-fast ease-standard',
        'motion-reduce:transition-none',
        'outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50',
        'disabled:cursor-not-allowed disabled:opacity-50',
        'data-[size=default]:h-[1.15rem] data-[size=default]:w-8',
        'data-[size=sm]:h-3.5 data-[size=sm]:w-6',
        'data-[state=checked]:bg-primary data-[state=unchecked]:bg-input',
        className,
      )}
      {...props}
    >
      <SwitchPrimitive.Thumb
        data-slot="switch-thumb"
        className={cn(
          'pointer-events-none block rounded-full bg-card ring-0',
          'transition-transform duration-fast ease-standard motion-reduce:transition-none',
          'group-data-[size=default]/switch:size-4 group-data-[size=sm]/switch:size-3',
          // Translated rather than justified: a flex jump has no intermediate state,
          // so the thumb would teleport and the control would feel broken rather
          // than switched.
          'data-[state=checked]:translate-x-[calc(100%-2px)] data-[state=unchecked]:translate-x-0',
        )}
      />
    </SwitchPrimitive.Root>
  );
}

export { Switch };
