import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { Tabs as TabsPrimitive } from 'radix-ui';

import { cn } from '../lib/utils.js';

/**
 * Generated by the shadcn CLI, then re-skinned. Same rules as `toggle.tsx`.
 *
 * **Nothing renders this yet, and that is deliberate rather than an oversight.**
 * It is here so that the shape exists when a surface finally switches between
 * panels of content. Nothing in the product does today: `/translate`, `/history`
 * and the rest are routes, which is the right answer for something that should
 * have a shareable URL and answer to the back button.
 *
 * It is emphatically NOT what the segmented controls are built on. Direction,
 * voice and theme set a VALUE; they do not reveal a panel. Tabs without a
 * tabpanel announces "tab, 1 of 2" and then leaves the reader looking for
 * content that does not exist. `SegmentedControl` uses `ToggleGroup`, which
 * renders a radio group.
 *
 * Stock shadcn also paints the active trigger and nothing else — the mark jumps
 * between triggers with nothing connecting the positions. If a real consumer
 * arrives, the sliding indicator in `SegmentedControl` is the pattern to copy.
 */

function Tabs({
  className,
  orientation = 'horizontal',
  ...props
}: React.ComponentProps<typeof TabsPrimitive.Root>) {
  return (
    <TabsPrimitive.Root
      data-slot="tabs"
      data-orientation={orientation}
      orientation={orientation}
      className={cn('group/tabs flex gap-2 data-[orientation=horizontal]:flex-col', className)}
      {...props}
    />
  );
}

const tabsListVariants = cva(
  [
    'group/tabs-list inline-flex w-fit items-center justify-center rounded-lg p-[3px]',
    'text-muted-foreground',
    'group-data-[orientation=horizontal]/tabs:h-9',
    'group-data-[orientation=vertical]/tabs:h-fit group-data-[orientation=vertical]/tabs:flex-col',
    'data-[variant=line]:rounded-none',
  ].join(' '),
  {
    variants: {
      variant: {
        default: 'bg-muted',
        line: 'gap-1 bg-transparent',
      },
    },
    defaultVariants: {
      variant: 'default',
    },
  },
);

function TabsList({
  className,
  variant = 'default',
  ...props
}: React.ComponentProps<typeof TabsPrimitive.List> & VariantProps<typeof tabsListVariants>) {
  return (
    <TabsPrimitive.List
      data-slot="tabs-list"
      data-variant={variant}
      className={cn(tabsListVariants({ variant }), className)}
      {...props}
    />
  );
}

function TabsTrigger({ className, ...props }: React.ComponentProps<typeof TabsPrimitive.Trigger>) {
  return (
    <TabsPrimitive.Trigger
      data-slot="tabs-trigger"
      className={cn(
        [
          'relative inline-flex h-[calc(100%-1px)] flex-1 items-center justify-center gap-1.5',
          'rounded-md border border-transparent px-2 py-1',
          'text-body font-medium whitespace-nowrap text-prose',
          'transition-[color,background-color,box-shadow] duration-fast ease-standard',
          'motion-reduce:transition-none',
          'group-data-[orientation=vertical]/tabs:w-full',
          'group-data-[orientation=vertical]/tabs:justify-start',
          'hover:text-foreground',
          'focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50',
          'focus-visible:outline-1 focus-visible:outline-ring',
          'disabled:pointer-events-none disabled:opacity-50',
          "[&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
        ].join(' '),
        'group-data-[variant=default]/tabs-list:data-[state=active]:shadow-elev-sm',
        'group-data-[variant=line]/tabs-list:data-[state=active]:shadow-none',
        'group-data-[variant=line]/tabs-list:bg-transparent',
        'group-data-[variant=line]/tabs-list:data-[state=active]:bg-transparent',
        // Ink, not the accent: a selected tab states the current view, it is not
        // the one action the screen exists to offer.
        'data-[state=active]:bg-card data-[state=active]:text-foreground',
        [
          'after:absolute after:bg-foreground after:opacity-0',
          'after:transition-opacity after:duration-base after:ease-standard',
          'motion-reduce:after:transition-none',
          'group-data-[orientation=horizontal]/tabs:after:inset-x-0',
          'group-data-[orientation=horizontal]/tabs:after:bottom-[-5px]',
          'group-data-[orientation=horizontal]/tabs:after:h-0.5',
          'group-data-[orientation=vertical]/tabs:after:inset-y-0',
          'group-data-[orientation=vertical]/tabs:after:-right-1',
          'group-data-[orientation=vertical]/tabs:after:w-0.5',
          'group-data-[variant=line]/tabs-list:data-[state=active]:after:opacity-100',
        ].join(' '),
        className,
      )}
      {...props}
    />
  );
}

function TabsContent({ className, ...props }: React.ComponentProps<typeof TabsPrimitive.Content>) {
  return (
    <TabsPrimitive.Content
      data-slot="tabs-content"
      className={cn('flex-1 outline-none', className)}
      {...props}
    />
  );
}

export { Tabs, TabsList, TabsTrigger, TabsContent, tabsListVariants };
