import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { Toggle as TogglePrimitive } from 'radix-ui';

import { cn } from '../lib/utils.js';

/**
 * Generated by the shadcn CLI, then re-skinned. Five things in its output are
 * wrong here and each is banned by `skin-guard.spec.ts`:
 *
 * - `text-sm` — the scale is by role, not by size name.
 * - `bg-accent` / `text-accent-foreground` — shadcn's `--accent` is a pale grey
 *   hover surface. Here the accent is *the* accent and a screen gets one
 *   accent-filled control, so a toggled segment is `bg-secondary`: ink, not
 *   colour. A segment says what the current value IS; it is not the action the
 *   screen exists to offer.
 * - `border-input` — this palette names that token `--border-control`.
 * - `dark:` variants — the palette is one `light-dark()` declaration and the
 *   theme class carries nothing, so a `dark:` utility never fires while every
 *   token still flips.
 * - `@/lib/utils` — resolves for the bundlers but not for `rollup-plugin-dts`,
 *   so it breaks the type build only.
 *
 * `shadow-xs` is replaced too, though no guard catches it: it was the CLI's
 * default rather than a decision, and there is a designed elevation scale now.
 */
const toggleVariants = cva(
  [
    'inline-flex items-center justify-center gap-2 rounded-md',
    'text-body font-medium whitespace-nowrap',
    'transition-[color,background-color,box-shadow] duration-fast ease-standard',
    'motion-reduce:transition-none',
    'outline-none hover:bg-muted',
    'focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50',
    'disabled:pointer-events-none disabled:opacity-50',
    'aria-invalid:border-destructive aria-invalid:ring-destructive/20',
    'data-[state=on]:bg-secondary data-[state=on]:text-foreground',
    "[&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
  ].join(' '),
  {
    variants: {
      variant: {
        default: 'bg-transparent',
        outline: 'border border-border-control bg-transparent shadow-elev-sm hover:bg-muted',
      },
      size: {
        default: 'h-9 min-w-9 px-2',
        sm: 'h-8 min-w-8 px-1.5',
        lg: 'h-10 min-w-10 px-2.5',
      },
    },
    defaultVariants: {
      variant: 'default',
      size: 'default',
    },
  },
);

function Toggle({
  className,
  variant,
  size,
  ...props
}: React.ComponentProps<typeof TogglePrimitive.Root> & VariantProps<typeof toggleVariants>) {
  return (
    <TogglePrimitive.Root
      data-slot="toggle"
      className={cn(toggleVariants({ variant, size, className }))}
      {...props}
    />
  );
}

export { Toggle, toggleVariants };
