import * as React from 'react';
import { type VariantProps } from 'class-variance-authority';
import { ToggleGroup as ToggleGroupPrimitive } from 'radix-ui';

import { cn } from '../lib/utils.js';
import { toggleVariants } from './toggle.js';

/**
 * Generated by the shadcn CLI, then re-skinned. See `toggle.tsx` for the list of
 * things the CLI writes that are wrong here; the same rules apply.
 *
 * **What `type="single"` actually renders, because it is not what the name
 * suggests.** Radix gives the Root `role="radiogroup"` and each item
 * `role="radio"` with `aria-checked`, deleting `aria-pressed` outright. So a
 * single-select ToggleGroup is a radio group as far as assistive technology is
 * concerned — the same contract `SegmentedControl` had when it wrapped
 * `RadioGroup` directly.
 *
 * The behaviour does NOT follow the role, and that gap is the thing to know.
 * Radix uses roving focus here: arrow keys move focus and selection waits for
 * Enter, Space or a click. A radio group is supposed to select as it moves, so
 * left alone this announces "radio, 1 of 3" and then ignores the arrow key the
 * announcement invites. `SegmentedControl` closes that itself rather than
 * shipping the mismatch — see the note there.
 */

const ToggleGroupContext = React.createContext<
  VariantProps<typeof toggleVariants> & { spacing?: number }
>({
  size: 'default',
  variant: 'default',
  spacing: 0,
});

function ToggleGroup({
  className,
  variant,
  size,
  spacing = 0,
  children,
  ...props
}: React.ComponentProps<typeof ToggleGroupPrimitive.Root> &
  VariantProps<typeof toggleVariants> & { spacing?: number }) {
  return (
    <ToggleGroupPrimitive.Root
      data-slot="toggle-group"
      data-variant={variant}
      data-size={size}
      data-spacing={spacing}
      style={{ '--gap': spacing } as React.CSSProperties}
      className={cn(
        'group/toggle-group flex w-fit items-center gap-[--spacing(var(--gap))] rounded-md',
        'data-[spacing=default]:data-[variant=outline]:shadow-elev-sm',
        className,
      )}
      {...props}
    >
      <ToggleGroupContext.Provider value={{ variant, size, spacing }}>
        {children}
      </ToggleGroupContext.Provider>
    </ToggleGroupPrimitive.Root>
  );
}

function ToggleGroupItem({
  className,
  children,
  variant,
  size,
  ...props
}: React.ComponentProps<typeof ToggleGroupPrimitive.Item> & VariantProps<typeof toggleVariants>) {
  const context = React.useContext(ToggleGroupContext);

  return (
    <ToggleGroupPrimitive.Item
      data-slot="toggle-group-item"
      data-variant={context.variant || variant}
      data-size={context.size || size}
      data-spacing={context.spacing}
      className={cn(
        toggleVariants({
          variant: context.variant || variant,
          size: context.size || size,
        }),
        'w-auto min-w-0 shrink-0 px-3 focus:z-10 focus-visible:z-10',
        'data-[spacing=0]:rounded-none data-[spacing=0]:shadow-none',
        'data-[spacing=0]:first:rounded-l-md data-[spacing=0]:last:rounded-r-md',
        'data-[spacing=0]:data-[variant=outline]:border-l-0',
        'data-[spacing=0]:data-[variant=outline]:first:border-l',
        className,
      )}
      {...props}
    >
      {children}
    </ToggleGroupPrimitive.Item>
  );
}

export { ToggleGroup, ToggleGroupItem };
