# yaml-language-server: $schema=https://releases.agentkit.best/schemas/config/v1.json
statusline: full
statusline_layout:
    max_agent_rows: 4
    responsive_breakpoint: 0.85
    section_config:
        changes:
            color: auto
        quota:
            icon: ⌛
    sections:
        - enabled: true
          id: model
          order: 0
        - enabled: true
          id: context
          order: 1
        - enabled: true
          id: quota
          order: 2
        - enabled: true
          id: directory
          order: 3
        - enabled: true
          id: git
          order: 4
        - enabled: true
          id: plan
          order: 5
        - enabled: false
          id: cost
          order: 6
        - enabled: true
          id: changes
          order: 7
        - enabled: true
          id: agents
          order: 8
        - enabled: true
          id: todos
          order: 9
    todo_truncation: 50
